### ISSUE TITLE
《使用远程调试》章节中设置断点并执行时，启动执行命令是否应该使用continue而不是文档中使用的run

### ISSUE THREAD

**Issue by markjenny** [objectkuan/ucore_docs#3]
在用gdb进行远程调试时，gdb一般认为被远程调试的程序已经时正在运行的了，此时使用run命令会报错：
```
The "remote" target does not support "run".
```
所以文档这里的是否应该使用continue进行程序的执行？

相关的资料：https://sourceware.org/gdb/onlinedocs/gdb/Starting.html

> Other targets, like ‘remote’, are always running. If you get an error message like this one:

The "remote" target does not support "run".
Try "help target" or "continue".
then use continue to run your program.

**Comment by objectkuan** [comment]
Thanks for reporting. Sorry for the delay.
